// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return Shoes.app(function() {
      var style;
      this.status("starting");
      style = {
        stroke: 'black',
        fill: '#aa3377',
        strokewidth: 4
      };
      return this.rect(10, 10, 200, 200, style);
    });
  });

}).call(this);
