// Generated by CoffeeScript 1.3.1
(function() {
  var Para, exports;

  Para = (function() {

    Para.name = 'Para';

    function Para(container, text, style) {
      this.container = container;
      this.text = text;
      this.style = style;
      this.element = document.createElement("p");
      this.element.appendChild(document.createTextNode(this.text));
      this.container.appendChild(this.element);
      this;

    }

    return Para;

  })();

  exports = exports != null ? exports : window;

  exports.Para = Para;

}).call(this);
