// Generated by CoffeeScript 1.3.1
(function() {
  var App, Shoes, exports;

  App = (function() {

    App.name = 'App';

    function App(block) {
      this.block = block;
      this.canvas = document.getElementById('app-canvas');
      this.context = this.canvas.getContext('2d');
      this.container = document.getElementById('app-content');
      this.container.innerHTML = '';
      this.block();
    }

    App.prototype.rect = function(left, top, width, height, style) {
      var rect;
      if (style == null) {
        style = {};
      }
      rect = new Rect(this.context, left, top, width, height, style);
      return rect.draw();
    };

    App.prototype.para = function(text, style) {
      if (style == null) {
        style = {};
      }
      return new Para(this.container, text, style);
    };

    return App;

  })();

  Shoes = (function() {

    Shoes.name = 'Shoes';

    function Shoes() {}

    Shoes.app = function(block) {
      var app;
      return app = new App(block);
    };

    Shoes.sample = function() {
      return "Shoes.app ->\n  style = {\n    stroke: \"black\",\n    fill: \"mediumorchid\",\n    strokewidth: 4\n  }\n  @rect 10, 40, 200, 200, style\n  @para \"Here's a nice purple block to start with\"";
    };

    return Shoes;

  })();

  exports = exports != null ? exports : window;

  exports.Shoes = Shoes;

}).call(this);
